name: Build UWP

on: [push]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      max-parallel: 4

    steps:
    - uses: actions/checkout@v1
    - name: Generate and build
      run: |
        pipeline.ps1 -uwp -build
